# render.yaml
services:
  - type: web
    name: movie-ticket-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: APP_NAME
        value: MovieTicketAPI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_CIPHER
        value: AES-256-CBC
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false # will be set automatically by Render
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false # from Aiven console
      - key: DB_PORT
        sync: false # from Aiven console  
      - key: DB_DATABASE
        sync: false # from Aiven console
      - key: DB_USERNAME
        sync: false # from Aiven console
      - key: DB_PASSWORD
        sync: false # from Aiven console
      - key: DB_SSLMODE
        value: require
      - key: MYSQL_ATTR_SSL_CA
        value: /var/www/docker/ca.pem
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: true
      - key: FRONTEND_URL
        value: https://movie-ticket-murex.vercel.app
      - key: SANCTUM_STATEFUL_DOMAINS
        value: movie-ticket-murex.vercel.app
      - key: SESSION_DOMAIN
        value: .movie-ticket-murex.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://movie-ticket-murex.vercel.app
      - key: TRUSTED_PROXIES
        value: "*"
      - key: LOG_LEVEL
        value: debug
